### ISSUE TITLE
fatal error: postgres.h: No such file or directory

### ISSUE THREAD

**Issue by DrivenA** [ildus/clickhouse_fdw#101]
I have a problem when compiling and installing：

Building C object src/CMakeFiles/clickhouse_fdw.dir/clickhouse_fdw.c.o
/home/sigma@ouc/yza/clickhouse_fdw/src/clickhouse_fdw.c:14:10: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
          ^~~~~~~~~~~~
compilation terminated.

**Comment by mkabilov** [comment]
You need to install header files. 
e.g. via installing the packet  
postgresql-server-dev-XX

**Comment by DrivenA** [comment]
> You need to install header files.
> e.g. via installing the packet
> postgresql-server-dev-XX

I have installed postgresql 13 on my local Ubuntu server. But the "postgres.h" file was not found either. Please tell me how should I install it so that clickhouse_fdw can be used normally? Thanks!

**Comment by DrivenA** [comment]
I solved the problem perfectly after installing postgresql-server-dev-XX, thank you for your help, I will close this issue

**Comment by DrivenA** [comment]
I solved the problem perfectly after installing postgresql-server-dev-XX, thank you for your help, I will close this issue.
